/*

 BACKGROUND2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 19
   Tile set      : C:\Users\DXS01101\Zeugs\Gameboy projekt DHBW\backgroundtilestest.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmap2Width 32
#define backgroundmap2Height 19
#define backgroundmap2Bank 0

extern unsigned char backgroundmap2[];

/* End of BACKGROUND2.H */
